version: '3'
services:
  #PHP Service
  my_app:
    build:
      args:
        user: staff
      context: ./
      dockerfile: Dockerfile
    ports:
      - "4300:80"
    container_name: my_app_base
    restart: unless-stopped
    env_file: ./.env
    environment:
      - APP_WORKSPACE=laravel-with-docker-starter
    working_dir: /var/www
    volumes:
      - ./:/var/www/laravel-with-docker-starter:cached

